var pathConfig = {};

//pathConfig = ['/pricing', '/message_board/pricing', '/benefits/pricing', '/forum/pricing', '/discussion_board/pricing', '/bulletin_board/pricing', '/wordpress/pricing'];

pathConfig = ['/features', '/message_board/features', '/discussion_board/features', '/bulletin_board/features', '/wordpress/features', '/benefits/features', '/forum/features'];
/*pathConfig = ['/pricing', '/message_board/pricing', '/benefits/pricing', '/forum/pricing', '/discussion_board/pricing', '/bulletin_board/pricing', '/wordpress/pricing', '/features', '/message_board/features', '/discussion_board/features', '/bulletin_board/features', '/wordpress/features', '/benefits/features', '/forum/features', '/support', '/message_board/forum2.html', '/message_board/forum.html', '/message_board/discussion_board.html', '/message_board/bulletin_board.html', '/index.html', '/message_board/forum.html?utm_expid=.-j9jVEsiTr2b_bd5pczrCw.0&utm_referrer=', '/wordpress', '/reviews', '/tos', '/dmca', '/tool/members/login', '/tool/members/dashboard?action=showLiveChatPromo'];*/

/*pathConfig = ['/', '/register/members', '/calendar', '/search', '/latest', '/post/printadd', '/?action=markread', '/?action=categories#forums', '/?action=categories#filter-modal', '/?action=categories', '/categories', '/register/lost_pw', '/new', '/top?period=all', '/register?action=forumrules', '/register/search', '/register/members?sort=reputation&reverse=true&list=&search=&fieldid_fields=&period=month', '/register/members?sort=joindate&reverse=true&list=&search=&fieldid_fields=', '/?action=subscribed_forums'];*/

/*pathConfig.refPaths = ['/', '/register/members', '/calendar', '/search', '/profile/5026885', '/register/logout?userid=5026885', '/latest', '/post/printadd', '/?action=markread', '/?action=categories#forums', '/post/new-topic-by-test-8664423?pid=1296938600', '/post/new-topic-8664427', '/?action=categories#filter-modal', '/?action=categories', '/categories', '/?forum=611814', '/?forum=611815', '/?forum=611609', '/?forum=611610', '/?forum=611811', '/newevent?do=add&dd=18&mm=7&yy=2017&calendarid=40348', '/calendar/eventdetail?eventid=29682&calendarid=40348&date=2017-7-18', '/calendar/display?view=weekly&from_month=7&from_year=2017&calendarid=121953&weekid=4', '/calendar/display?view=weekly&from_month=7&from_year=2017&weekid=3', '/calendar/display?view=yearly&from_month=7&from_year=2017&weekid=&calendarid=121953', '/register/lost_pw', '/new', '/top?period=all', '/search?userid=5026885&do=who_posted&action=doSearch&threadid=8652424', '/register?action=forumrules', '/register/search', '/register/members?sort=reputation&reverse=true&list=&search=&fieldid_fields=&period=month', '/register/members?sort=joindate&reverse=true&list=&search=&fieldid_fields=', '/?action=subscribed_forums', '/profile/5062712?dosearch=findThreads&searchid=55714903', '/profile/5062712?action=reputation&reputation=given', '/album?action=view_album&albumid=16419', '/album?userid=5062712'];

pathConfig.testPaths = ['/', '/register/members', '/calendar', '/search', '/profile/27714479', '/register/logout?userid=27714479', '/latest', '/post/printadd', '/?action=markread', '/?action=categories#forums', '/post/new-topic-by-test-12799870?pid=41172309', '/post/new-topic-12800443', '/?action=categories#filter-modal', '/?action=categories', '/categories', '/?forum=190532', '/?forum=190533', '/?forum=190554', '/?forum=190555', '/?forum=190556', '/newevent?do=add&dd=18&mm=7&yy=2017&calendarid=40348', '/calendar/eventdetail?eventid=29682&calendarid=40348&date=2017-7-18', '/calendar?view=weekly&from_month=7&from_year=2017&weekid=4&calendarid=40348', '/calendar/display?view=weekly&from_month=7&from_year=2017&weekid=3', '/calendar/display?view=yearly&from_month=7&from_year=2017&weekid=&calendarid=40348', '/register/lost_pw', '/new', '/top?period=all', '/search?userid=27714479&do=who_posted&action=doSearch&threadid=12799870', '/register?action=forumrules', '/register/search', '/register/members?sort=reputation&reverse=true&list=&search=&fieldid_fields=&period=month', '/register/members?sort=joindate&reverse=true&list=&search=&fieldid_fields=', '/?action=subscribed_forums', '/profile/27714479?dosearch=findThreads&searchid=19994', '/profile/27714479?action=reputation&reputation=given', '/album?action=view_album&albumid=1660', '/album?userid=27714479'];*/

/*pathConfig.refPaths = ['/'];

pathConfig.testPaths = ['/'];*/

module.exports = pathConfig;
